#!/usr/bin/env bash
set -euxo pipefail

dest="${1:-/usr/local}"

MOLD_VERSION="2.41.0"
curl -fsSL "https://github.com/rui314/mold/releases/download/v${MOLD_VERSION}/mold-${MOLD_VERSION}-x86_64-linux.tar.gz" \
  | tar -xz --strip-components=1 -C "${dest}"

"${dest}/bin/mold" --version
