#!/usr/bin/env bash
set -euxo pipefail

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq --yes
apt-get install -qq --no-install-recommends --yes \
  libasound2 \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libatspi2.0-0 \
  libcairo2 \
  libcups2 \
  libdbus-1-3 \
  libgbm1 \
  libglib2.0-0 \
  libgtk-3-0 \
  libnss3 \
  libpango-1.0-0 \
  libx11-6 \
  libxcomposite1 \
  libxdamage1 \
  libxext6 \
  libxfixes3 \
  libxkbcommon0 \
  libxrandr2 \
  libdrm2 \
  libxshmfence1 \
  libxcb1 \
  mesa-utils \
  libgl1-mesa-dri \
  libgl1-mesa-glx \
  dbus \
  xdg-utils \
>/dev/null
rm -rf /var/lib/apt/lists/*
apt-get clean autoclean >/dev/null
apt-get autoremove --yes >/dev/null
