#!/usr/bin/env bash
set -euxo pipefail

triplet="${1}"
dest=${2:-"/usr/local/${triplet}"}
mkdir -p "${dest}"

curl -fsSL "https://github.com/binarylandia/build_openblas/releases/download/2026-08-17_15-28-38/openblas-static-0.3.28-${triplet}-2026-08-17_15-28-38.tar.xz" \
  | pixz -dp "$(nproc)" \
  | tar -C "${dest}" -x

ls "${dest}/lib/libopenblas.a"
