#!/usr/bin/env bash
#
# Usage: $0 <prefix>
#
# Install LLVM and Clang 19, which bindgen needs (libclang), into a prefix.
#
set -euxo pipefail

dest="${1:?prefix}"
release="llvm-19.1.5-2024-12-21_14-43-03"
archive="/tmp/llvm.tar.gz"
mkdir -p "${dest}"

/fetch "https://github.com/binarylandia/build_llvm/releases/download/${release}/${release}.tar.gz" "${archive}"
pigz -dc -p "$(nproc)" "${archive}" | tar -C "${dest}" -x
rm "${archive}"
"${dest}/bin/clang" --version
