#!/usr/bin/env bash
set -euxo pipefail

dest=${1:-"/usr/local"}
mkdir -p "${dest}"

curl -fsSL "https://github.com/binarylandia/build_llvm/releases/download/llvm-19.1.3-2024-11-03_15-15-54/llvm-19.1.3-2024-11-03_15-15-54.tar.xz" \
  | pixz -dp "$(nproc)" \
  | tar -C "${dest}" -x

ls "${dest}/bin/clang"
"${dest}/bin/clang" -v

ls "${dest}/bin/llvm-ar"
"${dest}/bin/llvm-ar" --version
