#!/usr/bin/env bash
set -euxo pipefail

dest="${1:-/usr/local}"
mkdir -p "${dest}/bin"

SCCACHE_VERSION="0.13.0"
curl -fsSL "https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl.tar.gz" \
  | tar --strip-components=1 -C "${dest}/bin" -xz "sccache-v${SCCACHE_VERSION}-x86_64-unknown-linux-musl/sccache"

"${dest}/bin/sccache" --version
