#!/usr/bin/env bash
set -euxo pipefail

dest=${1:-"/usr/local"}
mkdir -p "${dest}/bin"

version="1.19.0"

curl -fsSL "https://github.com/sharkdp/hyperfine/releases/download/v${version}/hyperfine-v${version}-x86_64-unknown-linux-gnu.tar.gz" \
  | tar --strip-components=1 -C "${dest}/bin" -xz "hyperfine-v${version}-x86_64-unknown-linux-gnu/hyperfine"

ls "${dest}/bin/hyperfine"
hyperfine --version
