#!/usr/bin/env bash
set -euxo pipefail

dest=${1:-"/usr/local"}
mkdir -p "${dest}"

curl -fsSL "https://github.com/binarylandia/build_llvm/releases/download/llvm-19.1.5-2024-12-21_14-43-03/llvm-19.1.5-2024-12-21_14-43-03.tar.gz" \
  | pigz -d -p "$(nproc)" \
  | tar -C "${dest}" -x

ls "${dest}/bin/clang"
"${dest}/bin/clang" -v

ls "${dest}/bin/llvm-ar"
"${dest}/bin/llvm-ar" --version
