#!/usr/bin/env bash
set -euxo pipefail

triplet=${1}
dest=${2:-"/opt/rust-${1}"}
mkdir -p "${dest}"

export PATH="${dest}/bin:${PATH:+":${PATH}"}"

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --default-toolchain=none

rustup set profile minimal

if [ ! -f "${dest}/rust-toolchain.toml" ]; then
  echo "$0: file not found: '${dest}/rust-toolchain.toml'" >&2
  exit 1
fi

# `rustup show` installs toolchain version specified in `rust-toolchain.toml` in the current directory
cd "${dest}"
rustup show

rustup component add clippy rustfmt llvm-tools-preview

if [ -n "${triplet:-}" ]; then
  rustup target add "${triplet}"
fi

rustc --version --verbose
cargo --version --verbose

CARGO_NEXTEST_VERSION="0.9.67"
curl -sSL "https://github.com/nextest-rs/nextest/releases/download/cargo-nextest-${CARGO_NEXTEST_VERSION}/cargo-nextest-${CARGO_NEXTEST_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -C "${dest}/bin" -xz "cargo-nextest"
chmod +x "${dest}/bin/cargo-nextest"
cargo nextest --version --verbose

CARGO_LLVM_COV_VERSION="0.8.5"
curl -sSL "https://github.com/taiki-e/cargo-llvm-cov/releases/download/v${CARGO_LLVM_COV_VERSION}/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz" | tar -C "${dest}/bin" -xz "cargo-llvm-cov"
chmod +x "${dest}/bin/cargo-llvm-cov"
cargo llvm-cov --version

CARGO_SHEAR_VERSION="1.11.2"
curl -sSL "https://github.com/Boshen/cargo-shear/releases/download/v${CARGO_SHEAR_VERSION}/cargo-shear-x86_64-unknown-linux-gnu.tar.gz" | tar -C "${dest}/bin" -xz "cargo-shear"
chmod +x "${dest}/bin/cargo-shear"
cargo shear --version

CARGO_EDIT_VERSION="0.13.7"
cargo -q install --locked cargo-edit --version "${CARGO_EDIT_VERSION}"
cargo upgrade --version

BACON_VERSION="3.23.0"
cargo -q install --locked bacon --version "${BACON_VERSION}"
bacon --version
