#!/usr/bin/env bash
#
# Usage: $0 <prefix>
#
# Install the osxcross toolchain and the macOS SDK into a prefix.
#
set -euxo pipefail

dest="${1:?prefix}"
release="2024-12-22_17-20-35"
archive="/tmp/osxcross.tar.xz"
mkdir -p "${dest}"

/fetch "https://github.com/binarylandia/build_osxcross/releases/download/${release}/osxcross-full-41f3856-${release}.tar.xz" "${archive}"
pixz -dp "$(nproc)" <"${archive}" | tar -C "${dest}" -x
rm "${archive}"
