#!/usr/bin/env bash
set -euxo pipefail

dest=${1:-"/opt/osxcross"}
mkdir -p "${dest}"

curl -fsSL "https://github.com/binarylandia/build_osxcross/releases/download/2024-12-22_17-20-35/osxcross-full-41f3856-2024-12-22_17-20-35.tar.xz" \
  | pixz -dp "$(nproc)" \
  | tar -C "${dest}" -x
