default_job = "check"

[jobs.check]
command = ["cargo", "clippy", "--all-targets", "--workspace", "--target-dir=.build/docker"]
need_stdout = false

[jobs.server]
command = ["bash", "-c", "printf 'Compiling server...\\n' >&2 && exec dev/dev r treetime-server -- --data-dir=data --out-dir=tmp/web"]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
kill = ["kill", "-s", "TERM"]
