#!/usr/bin/env bash

set -euo pipefail

function abspath() {
  readlink -m "$1"
}


declare -a TARGETS=(
  "aarch64-apple-darwin"
  "aarch64-unknown-linux-gnu"
  "aarch64-unknown-linux-musl"
  "x86_64-apple-darwin"
  "x86_64-pc-windows-gnu"
  "x86_64-unknown-linux-gnu"
  "x86_64-unknown-linux-musl"
)


for target in "${TARGETS[@]}"; do
  printf "\nBuilding for %s\n" "${target}"
  CROSS=${target} ./docker-dev br
done

