#!/usr/bin/env bash

set -euo pipefail

function abspath() {
  readlink -m "$1"
}

export THIS_DIR=$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd
)

SUCCESS="({ set +x; } 2> /dev/null && echo '🟩 Success' && exit 0)"
FAILURE="({ set +x; } 2> /dev/null && echo '🟥 Failure' && exit 1)"
CANCELLED="({ set +x; } 2> /dev/null && echo '🟦 Cancelled' && exit 0)"
SUCCESS_OR_FAILURE="&& ${SUCCESS} || ${FAILURE}"
HANDLE_SIGINT="trap \"${CANCELLED}; exit 0\" INT"

export PACKAGE_NAME="treetime"
export PACKAGE_DIR_REL=""

export PROJECT_ROOT_DIR="$(abspath "${THIS_DIR}")"
export PACKAGE_DIR="$(abspath "${PROJECT_ROOT_DIR}/${PACKAGE_DIR_REL}")"

export DOCKER_IMAGE_NAME="${PACKAGE_NAME}-dev"
export DOCKER_CONTAINER_NAME="${DOCKER_IMAGE_NAME//\//-}-$(date +%s)"

export USER=user
export GROUP=user

export BUILD_DIR_REL=".build/docker/${PACKAGE_DIR_REL}"
export BUILD_DIR="$(abspath "${PACKAGE_DIR}/${BUILD_DIR_REL}")"
export BUILD_DIR_TEST="${BUILD_DIR}/test"

export CACHE_DIR_REL=".cache/docker/${PACKAGE_DIR_REL}"
export CACHE_DIR="$(abspath "${PACKAGE_DIR}/${CACHE_DIR_REL}")"

export NICE="nice -14 ionice -c2 -n3"
export TIME="/usr/bin/time --quiet -f \"Cmd : %C\nTime: %E\nMem : %M KB\n\""

export RUST_BACKTRACE="full"
export COLORBT_SHOW_HIDDEN="0"
export RUST_LOG="warn"
export CARGO_BUILD_TARGET_DIR="${BUILD_DIR_REL}"

export EXTENSIONS_TO_WATCH="rs,toml,lock"

export FILES_TO_WATCH="\
-w 'Cargo.lock' \
-w 'Cargo.toml' \
-w 'clippy.toml' \
-w 'packages/treetime/src' \
-w 'packages/treetime/Cargo.toml' \
-w 'rust-toolchain.toml' \
-w 'rustfmt.toml' \
"

export FILES_TO_IGNORE="\
-i '.build' \
-i '.cache' \
-i '.vscode' \
-i 'target/' \
"

export LINT_FIX="--fix --allow-staged"

BUILD=0
RUN=0
WASM=0
WEB=0
RELEASE=
WATCH=0
TEST=0
TEST_FLAGS=
BENCH=0
EXAMPLE=0
LINT=0
FIX=

case "${1:-}" in
"build" | "b")
  shift
  BUILD=1
  ;;
"build-release" | "br")
  shift
  BUILD=1
  RELEASE="--release"
  ;;
"run" | "r")
  shift
  RUN=1
  ;;
"run-release" | "rr")
  shift
  RUN=1
  RELEASE="--release"
  ;;
"watch-run" | "wr")
  shift
  RUN=1
  WATCH=1
  ;;
"watch-run-release" | "wrr")
  shift
  RUN=1
  RELEASE="--release"
  WATCH=1
  ;;
"test" | "t")
  shift
  TEST=1
  WATCH=0
  ;;
"watch-test" | "wt")
  shift
  TEST=1
  WATCH=1
  ;;
"test-unit" | "tu")
  shift
  TEST=1
  TEST_FLAGS="--lib"
  WATCH=0
  ;;
"watch-test-unit" | "wtu")
  shift
  TEST=1
  TEST_FLAGS="--lib"
  WATCH=1
  ;;
"test-integration" | "ti")
  shift
  TEST=1
  TEST_FLAGS="--test='*'"
  WATCH=0
  ;;
"watch-test-integration" | "wti")
  shift
  TEST=1
  TEST_FLAGS="--test='*'"
  WATCH=1
  ;;
"bench" | "B")
  shift
  BENCH=1
  WATCH=0
  ;;
"watch-bench" | "wB")
  shift
  BENCH=1
  WATCH=1
  ;;
"example" | "E")
  shift
  EXAMPLE=1
  ;;
"example-release" | "Er")
  shift
  EXAMPLE=1
  RELEASE="--release"
  ;;
"lint" | "l")
  shift
  LINT=1
  WATCH=0
  FIX=
  ;;
"watch-lint" | "wl")
  shift
  LINT=1
  WATCH=1
  FIX=
  ;;
"lint-fix" | "lf")
  shift
  LINT=1
  WATCH=0
  FIX="${LINT_FIX}"
  ;;
"watch-lint-fix" | "wlf")
  shift
  LINT=1
  WATCH=1
  FIX="${LINT_FIX}"
  ;;
"exec" | "e")
  shift
  RUN=0
  ;;
esac

if [ "${WASM}" == "1" ]; then
  CROSS="wasm32-unknown-unknown"
fi

DOCKER_TARGET="dev"
DOCKER_TAG="latest"
RUST_TARGET=""
if [ -n "${CROSS:-}" ]; then
  DOCKER_TARGET="cross-${CROSS}"
  DOCKER_TAG="cross-${CROSS}"
  RUST_TARGET="--target=${CROSS}"
fi

DOCKER_BUILD_ARGS=""
MACOS_SDK_FILENAME="MacOSX11.1.sdk.tar.xz"
MACOS_SDK_SHA="4a575e099c1b5dafe2835770d2a225c4ed082c2a36ecec9eac0946339fe665f3"
if [[ "${CROSS:-}" == *-apple-darwin ]]; then
  DOCKER_BUILD_ARGS=" \
    --build-arg MACOS_SDK_FILENAME=${MACOS_SDK_FILENAME} \
    --build-arg MACOS_SDK_SHA=${MACOS_SDK_SHA} \
  "
fi

# shellcheck disable=SC2086
docker build -q -t "${DOCKER_IMAGE_NAME}:${DOCKER_TAG}" \
  -f "${PACKAGE_DIR}/docker-dev.dockerfile" \
  --target="${DOCKER_TARGET}" \
  --build-arg="UID=$(id -u)" \
  --build-arg="GID=$(id -g)" \
  --build-arg="USER=user" \
  --build-arg="GROUP=user" \
  --network=host \
  ${DOCKER_BUILD_ARGS} \
  "${PACKAGE_DIR}" \
  >/dev/null

export RUSTC_FORCE_INCREMENTAL=""
if [ -n "${RELEASE}" ]; then
  export RUSTC_FORCE_INCREMENTAL=1
fi

COMMAND=${*:-}
PORTS=
if [ "${RUN}" == "1" ]; then
  PARAMS="$(echo "${@:-}" | xargs)"
  if [ -n "${PARAMS}" ]; then
    PARAMS="--bin=${PARAMS}"
  fi
  COMMAND="cargo run -q --target-dir='${BUILD_DIR_REL}' ${RUST_TARGET} ${RELEASE} ${PARAMS}"
elif [ "${EXAMPLE}" == "1" ]; then
  PARAMS="$(echo "${@:-}" | xargs)"
  if [ -n "${PARAMS}" ]; then
    PARAMS="--example=${PARAMS}"
  fi
  COMMAND="cargo run -q --target-dir='${BUILD_DIR_REL}' ${RUST_TARGET} ${RELEASE} ${PARAMS}"
elif [ "${BUILD}" == "1" ]; then
  COMMAND="cargo build -q --target-dir='${BUILD_DIR_REL}' ${RUST_TARGET} ${RELEASE} ${PARAMS}"
elif [ "${TEST}" == "1" ]; then
  PRETTY_TEST="( grep --color=always --line-buffered -vP \"running.*tests|\x1b\[32m.\x1b\(B\x1b\[m|^$|test result|TEST START\" || true )"
  COMMAND="cargo test --color=always -q --target-dir='${BUILD_DIR_REL}' ${RUST_TARGET} ${TEST_FLAGS} ${*:-} -- --nocapture --color=always | ${PRETTY_TEST} ${SUCCESS_OR_FAILURE}"
elif [ "${BENCH}" == "1" ]; then
  PRETTY_BENCH="( grep --color=always --line-buffered -vP \"Benchmarking|Gnuplot not found, using plotters backend\" || true )"
  COMMAND="cargo bench --color=always -q --target-dir='${BUILD_DIR_REL}' ${RUST_TARGET} ${*:-} | ${PRETTY_BENCH} ${SUCCESS_OR_FAILURE}"
elif [ "${LINT}" == "1" ]; then
  COMMAND="cargo clippy --exclude=3rdparty -q --target-dir=\"${BUILD_DIR_REL}\" --all ${FIX:-}"
else
  COMMAND="${NICE} ${TIME} ${COMMAND}"
fi

if [ "${WATCH}" == "1" ]; then
  COMMAND="${NICE} watchexec \
    --restart \
    --shell=bash \
    --debounce=10 \
    --no-meta \
    --no-environment \
    --exts=${EXTENSIONS_TO_WATCH} \
    ${FILES_TO_WATCH} \
    ${FILES_TO_IGNORE} \
    'reset; ${NICE} ${TIME} ${COMMAND}'"
else
  COMMAND="${NICE} ${TIME} ${COMMAND}"
fi

CPUS="$(($(nproc) - 2))"

mkdir -p "${BUILD_DIR}" "${CACHE_DIR}/.cargo/"{install,registry}

# shellcheck disable=SC2086
docker run -it --rm \
  --network=host \
  --init \
  --name="${DOCKER_CONTAINER_NAME}" \
  --hostname="${DOCKER_IMAGE_NAME}" \
  --user="$(id -u):$(id -g)" \
  --volume="${PROJECT_ROOT_DIR}:/workdir" \
  --volume="${CACHE_DIR}/.cargo/install:/home/${USER}/.cargo/install" \
  --volume="${CACHE_DIR}/.cargo/registry:/home/${USER}/.cargo/registry" \
  --workdir="/workdir/${PACKAGE_DIR_REL}" \
  --env="UID=$(id -u)" \
  --env="GID=$(id -g)" \
  --env="USER=${USER}" \
  --env="GROUP=${GROUP}" \
  --env="PS1=\${USER}@\${HOST}" \
  --env="RUST_BACKTRACE=${RUST_BACKTRACE}" \
  --env="COLORBT_SHOW_HIDDEN=${COLORBT_SHOW_HIDDEN}" \
  --env="RUST_LOG=${RUST_LOG}" \
  --env="CARGO_BUILD_TARGET_DIR=${CARGO_BUILD_TARGET_DIR}" \
  --env="RUSTC_FORCE_INCREMENTAL=${RUSTC_FORCE_INCREMENTAL}" \
  ${PORTS} \
  --cpus="${CPUS}" \
  "${DOCKER_IMAGE_NAME}:${DOCKER_TAG}" \
  bash -c "set -euo pipefail; ${HANDLE_SIGINT}; ${COMMAND} ${SUCCESS_OR_FAILURE}"
