import { noTautologicalAssertionRule } from "../rules/no-tautological-assertion.ts";
import { ruleTester } from "./rule-tester.ts";

const tester = ruleTester("ts", { NaN: "readonly", undefined: "readonly", Infinity: "readonly" });

const error = { messageId: "tautology" };

tester.run("treetime/no-tautological-assertion", noTautologicalAssertionRule, {
  valid: [
    "import { value, advance } from './counter'; const before = value; advance(); assert.strictEqual(before, value)",
    "import value, { advance } from './counter'; const before = value; advance(); expect(before).toBe(value)",
    "expect(total).toBe(3)",
    "expect(total).not.toBe(other)",
    "await expect(promise).resolves.toEqual(expected)",
    "assert.strictEqual(config.port, 8140)",
    "assert(total === expected)",
    "expect(total).toBeDefined()",
    "expect(total).toBe(total)",
    "expect(total).not.toEqual(total)",
    "await expect(promise).resolves.toStrictEqual(promise)",
    "expect(config.port).toBe(config.port)",
    "expect(read()).toBe(read())",
    "assert(total === total)",
    "assert(total !== total)",
    "assert(total <= total)",
    "assert(total >= total)",
    "assert(1 !== 1)",
    "assert(1 != 1)",
    "assert(1 < 1)",
    "assert(1 > 1)",
    "assert(NaN === NaN)",
    "assert(NaN <= NaN)",
    "assert(NaN >= NaN)",
    "assert(NaN == NaN)",
    "assert(!true)",
    "assert(false)",
    "assert.ok(0)",
    "expect(true).not.toBe(true)",
    "expect(true).not.not.toBe(true)",
    "expect(true).toBeFalsy()",
    "expect(false).toBeTruthy()",
    "expect(total).not.toBeTruthy()",
    "expect(total).toBeFalsy()",
    "expect(NaN).not.toBe(NaN)",
    "expect(0).toBe(-0)",
    "expect({}).toBe({})",
    "expect([]).toBe([])",
    "expect({ x: 1 }).toEqual({ x: 2 })",
    "expect([]).not.toEqual([])",
    "expect([1]).toContain([1])",
    "expect(value).toContainEqual(value)",
    "const value = {}; expect(value).not.toBe(value)",
    "const value = {}; expect(value).not.toEqual(value)",
    "const value = NaN; assert(value === value)",
    "function check(value) { assert(value === value) }",
    "function check(NaN) { assert(NaN !== NaN) }",
    "let value = 1; mutate(() => { value = 2 }); expect(value).toBe(1)",
    "assert.equal(1, '1')",
    "assert.notEqual(1, '1')",
    "assert.notStrictEqual(NaN, NaN)",
    "assert.notDeepStrictEqual(1, 1)",
    "const value = read(); expect(value).not.toBe(value)",
    "const promise = read(); await expect(promise).rejects.toBe(promise)",
    "if (condition) { var value = 1 } expect(value).toBe(1)",
    "function check(expect, assert) { expect(1).toBe(1); assert(1 === 1) }",
    "import { expect } from './custom'; expect(1).toBe(1)",
    "import assert from './custom'; assert.strictEqual(1, 1)",
    "import assert from 'node:assert/strict'; assert.equal(1, '1')",
    "import { strict as assert } from 'node:assert'; assert.equal(1, '1')",
    "import * as assert from 'node:assert'; assert(true)",
    "const left = {}; const right = {}; expect(left).toBe(right)",
    "expect(1 === 2).toBe(true)",
    "expect(total === total).toBe(true)",
    "expect(value).toBe(value); const value = 1",
  ],
  invalid: [
    { code: "import { default as check } from 'node:assert'; check(true)", errors: [error] },
    {
      code: "import { value, advance } from './counter'; const before = value; const alias = before; advance(); assert.strictEqual(before, alias)",
      errors: [error],
    },
    {
      code: "import * as values from './counter'; const alias = values; assert.strictEqual(values, alias)",
      errors: [error],
    },
    {
      code: "import { strictEqual } from 'node:assert'; function check() { type strictEqual = string; strictEqual(1, 1); }",
      errors: [error],
    },
    { code: "const total = 3; expect(total).toBe(total)", errors: [error] },
    { code: "const config = {}; assert.deepStrictEqual(config, config)", errors: [error] },
    { code: "const total = 3; assert(total === total)", errors: [error] },
    { code: "function check(value) { expect(value).toBe(value) }", errors: [error] },
    { code: "const value = read(); expect(value).toBe(value)", errors: [error] },
    { code: "const value = {}; const alias = value; expect(value).toBe(alias)", errors: [error] },
    { code: "const value = {}; assert(value === value)", errors: [error] },
    { code: "const value = []; expect(value).toStrictEqual(value)", errors: [error] },
    { code: "expect({}).not.toBe({})", errors: [error] },
    { code: "expect(/x/).not.toBe(/x/)", errors: [error] },
    { code: "assert(1 === 1)", errors: [{ ...error, column: 0, endColumn: 15 }] },
    { code: "assert(1 == '1')", errors: [error] },
    { code: "assert(1 !== 2)", errors: [error] },
    { code: "assert(1 != 2)", errors: [error] },
    { code: "assert(1 <= 1)", errors: [error] },
    { code: "assert(1 >= 1)", errors: [error] },
    { code: "assert(1 < 2)", errors: [error] },
    { code: "assert(2 > 1)", errors: [error] },
    { code: "assert(NaN !== NaN)", errors: [error] },
    { code: "assert(NaN != NaN)", errors: [error] },
    { code: "expect(NaN).toBe(NaN)", errors: [error] },
    { code: "expect(NaN).toStrictEqual(NaN)", errors: [error] },
    { code: "expect(0).not.toBe(-0)", errors: [error] },
    { code: "assert(0 === -0)", errors: [error] },
    { code: "assert(true)", errors: [error] },
    { code: "assert.ok('value')", errors: [error] },
    { code: "assert(!false)", errors: [error] },
    { code: "expect(true).toBeTruthy()", errors: [error] },
    { code: "expect(false).toBeFalsy()", errors: [error] },
    { code: "expect(true).not.toBeFalsy()", errors: [error] },
    { code: "expect(false).not.toBeTruthy()", errors: [error] },
    { code: "expect(1).not.toEqual(2)", errors: [error] },
    { code: "assert.strictEqual(NaN, NaN)", errors: [error] },
    { code: "assert.equal(NaN, NaN)", errors: [error] },
    { code: "assert.notStrictEqual(1, 2)", errors: [error] },
    { code: "assert.notDeepStrictEqual(1, 2)", errors: [error] },
    { code: "assert.notEqual(1, 2)", errors: [error] },
    { code: "assert.notDeepEqual(1, 2)", errors: [error] },
    { code: "expect(undefined).toBeFalsy()", errors: [error] },
    { code: "expect(null).toBeFalsy()", errors: [error] },
    { code: "expect(0n).toBeFalsy()", errors: [error] },
    { code: "expect(-1n).toBe(-1n)", errors: [error] },
    { code: "expect(`value`).toBe('value')", errors: [error] },
    { code: "expect(1 === 2).not.toBe(true)", errors: [error] },
    { code: "const left = {}; const right = {}; expect(left).not.toBe(right)", errors: [error] },
    { code: "import { expect as check } from 'vitest'; check(1).toBe(1)", errors: [error] },
    { code: "import assert from 'node:assert'; assert.equal(1, '1')", errors: [error] },
    { code: "import assert from 'node:assert/strict'; assert.notEqual(1, '1')", errors: [error] },
    {
      code: "import { strict as assert } from 'node:assert'; assert.notEqual(1, '1')",
      errors: [error],
    },
    { code: "import { strictEqual as check } from 'node:assert'; check(1, 1)", errors: [error] },
    { code: "import * as check from 'node:assert'; check.strictEqual(1, 1)", errors: [error] },
  ],
});
