name: intel-mkl

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --manifest-path=ndarray-linalg/Cargo.toml
            --no-default-features
            --features=intel-mkl-static

  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: >
            --manifest-path=ndarray-linalg/Cargo.toml
            --no-default-features
            --features=intel-mkl-static

  linux-container:
    runs-on: ubuntu-18.04
    container: ghcr.io/rust-math/intel-mkl-src/mkl-rust:1.49.0
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/cargo@v1
        name: cargo test
        with:
          command: test
          args: >
            --manifest-path=ndarray-linalg/Cargo.toml
            --no-default-features
            --features=intel-mkl-system
