name: netlib

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        feature:
          - static
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: apt install gfortran
        run: |
          sudo apt update
          sudo apt install -y gfortran
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --manifest-path=ndarray-linalg/Cargo.toml
            --no-default-features
            --features=netlib-${{ matrix.feature }}
