name: openblas

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  linux:
    runs-on: ubuntu-18.04
    container:
      image: rust
    strategy:
      fail-fast: false
      matrix:
        feature:
          - static
          - system
    steps:
      - uses: actions/checkout@v1
      - name: apt install gfortran
        run: |
          apt update
          apt install -y gfortran
      - name: Install OpenBLAS by apt
        run: |
          apt update
          apt install -y libopenblas-dev
        if: ${{ contains(matrix.feature, 'system') }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: >
            --manifest-path=ndarray-linalg/Cargo.toml
            --no-default-features
            --features=openblas-${{ matrix.feature }}
