#!/usr/bin/env python3

import re
import sys

patterns_multiline = [
  r'\n.*?PASS.*?\n\n.*STDOUT.*?---.*?\n\nrunning \d+ tests?(?s:.*?)test .*? ... ok\n\ntest result: (ok|FAILED). \d+ passed; \d+ failed; \d+ ignored; \d+ measured; \d+ filtered out; finished in .*?\n\n(?!--- STDERR)',

  r'test .* \.\.\. FAILED\n\nfailures:\n\nfailures:\n.*\n\ntest result: FAILED. \d+ passed; \d+ failed; \d+ ignored; \d+ measured; \d+ filtered out; finished in .*\n',

  r'\n-------------- TEST START --------------\n',

  r'\n.*STDOUT.*?\n\nrunning \d+ test',
]

patterns = [
  r'.*Starting.*test.*across.*binaries.*\n',
  r'.*------------.*\n',
  r'.*Summary.* run.*passed.*skipped.*\n',
]

s = sys.stdin.read()

for pattern in patterns_multiline:
  s = re.sub(pattern, '', s, flags=re.MULTILINE)

for pattern in patterns:
  s = re.sub(pattern, '', s)

text = '--- PARAMS:\n'
s = re.sub(r'\n------------ TEST ARGUMENTS ------------\n', f"\x1b[1;38;5;100m{text}\x1b[0m", s)

sys.stdout.write(s)
