# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: taxodium.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'taxodium.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etaxodium.proto\x12\x08Taxodium\" \n\x0cMutationList\x12\x10\n\x08mutation\x18\x01 \x03(\x05\"q\n\x1aMetadataSingleValuePerNode\x12\x15\n\rmetadata_name\x18\x01 \x01(\t\x12\x16\n\x0emetadata_title\x18\x02 \x01(\t\x12\x0f\n\x07mapping\x18\x03 \x03(\t\x12\x13\n\x0bnode_values\x18\x04 \x03(\x05\"\x9f\x02\n\x0b\x41llNodeData\x12\r\n\x05names\x18\x01 \x03(\t\x12\t\n\x01x\x18\x02 \x03(\x02\x12\t\n\x01y\x18\x03 \x03(\x02\x12\x11\n\tcountries\x18\x04 \x03(\x05\x12\r\n\x05\x64\x61tes\x18\x07 \x03(\x05\x12\x10\n\x08lineages\x18\x05 \x03(\x05\x12)\n\tmutations\x18\x06 \x03(\x0b\x32\x16.Taxodium.MutationList\x12\x0f\n\x07parents\x18\x08 \x03(\x05\x12\x10\n\x08genbanks\x18\t \x03(\t\x12\x17\n\x0f\x65pi_isl_numbers\x18\n \x03(\x05\x12\x10\n\x08num_tips\x18\x0b \x03(\x05\x12>\n\x10metadata_singles\x18\x0c \x03(\x0b\x32$.Taxodium.MetadataSingleValuePerNode\"\xc3\x01\n\x07\x41llData\x12(\n\tnode_data\x18\x01 \x01(\x0b\x32\x15.Taxodium.AllNodeData\x12\x17\n\x0f\x63ountry_mapping\x18\x02 \x03(\t\x12\x17\n\x0flineage_mapping\x18\x03 \x03(\t\x12\x18\n\x10mutation_mapping\x18\x04 \x03(\t\x12\x14\n\x0c\x64\x61te_mapping\x18\x05 \x03(\t\x12\x18\n\x10tree_description\x18\x06 \x01(\t\x12\x12\n\ntree_title\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'taxodium_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MUTATIONLIST']._serialized_start=28
  _globals['_MUTATIONLIST']._serialized_end=60
  _globals['_METADATASINGLEVALUEPERNODE']._serialized_start=62
  _globals['_METADATASINGLEVALUEPERNODE']._serialized_end=175
  _globals['_ALLNODEDATA']._serialized_start=178
  _globals['_ALLNODEDATA']._serialized_end=465
  _globals['_ALLDATA']._serialized_start=468
  _globals['_ALLDATA']._serialized_end=663
# @@protoc_insertion_point(module_scope)
