mod test_fitch;
mod test_marginal_analytical;
mod test_marginal_branch_length;
mod test_marginal_consistency;
mod test_marginal_dense;
mod test_marginal_sparse;
mod test_marginal_stability;
mod test_marginal_topology;
mod test_python_parity;
