#!/usr/bin/env bash

# Runs bulk cross-compilation of CLI binaries for all supported platforms

set -euo pipefail

function abspath() {
  readlink -m "$1"
}

targets=(
  "aarch64-apple-darwin"
  "aarch64-unknown-linux-gnu"
  "aarch64-unknown-linux-musl"
  "x86_64-apple-darwin"
  "x86_64-pc-windows-gnu"
  "x86_64-unknown-linux-gnu"
  "x86_64-unknown-linux-musl"
)

function run_one() {
  target=${1:?}
  printf "\nBuilding for %s\n" "${target}"
  CROSS=${target} ./docker/dev br
}
export -f run_one

parallel --jobs="${#targets[@]}" run_one ::: "${targets[@]}"
