[package]
name = "treetime-cli"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true


[dependencies]
clap = { workspace = true }
clap_complete = { workspace = true }
clap_complete_fig = { workspace = true }
color-eyre = { workspace = true }
ctor = { workspace = true }
eyre = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
maplit = { workspace = true }
num_cpus = { workspace = true }
pretty_assertions = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
treetime = { path = "../treetime" }

[lints]
workspace = true
