[package]
name = "treetime"
description = "Maximum-likelihood phylodynamic inference"
version = "4.0.0"
documentation = "https://treetime.readthedocs.io/en/stable/"
homepage = "https://github.com/neherlab/treetime"
edition = "2021"
license = "MIT"
publish = false
keywords = ["phylogenetics", "phylogeography", "virus", "evolution"]


[lib]
crate-type = ["lib"]

[dependencies]
approx = "0.5.1"
argmin = { version = "0.5.1", features = ["ctrlc", "ndarray"] }
atty = "0.2.14"
bio = { version = "0.41.0", features = ["phylogeny"] }
bio-types = { version = "0.12.1", features = ["phylogeny"] }
bzip2 = "0.4.3"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
clap = { version = "3.1.8", features = ["derive"] }
clap-verbosity-flag = "1.0.0"
clap_complete = "3.1.1"
clap_complete_fig = "3.1.4"
color-eyre = "0.6.1"
ctor = "0.1.22"
derive_more = { version = "0.99.17" }
env_logger = "0.9.0"
eyre = "0.6.8"
flate2 = "1.0.24"
float-cmp = "0.9.0"
indexmap = { version = "1.9.1", features = ["serde-1"] }
itertools = "0.10.3"
itertools-num = "0.1.3"
lazy_static = "1.4.0"
log = "0.4.16"
num = "0.4.0"
num-integer = "0.1.44"
num-traits = "0.2.14"
owo-colors = "3.3.0"
parking_lot = { version = "0.12.1", features = ["deadlock_detection", "hardware-lock-elision"] }
petgraph = "0.6.2"
rand = { version = "0.8.5", features = ["serde1", "log"] }
rand_distr = { version = "0.4.3", feaures = ["serde1", "std_math"] }
rand_isaac = { version = "0.3.0", features = ["serde1"] }
rand_pcg = { version = "0.3.1", features = ["serde1"] }
rayon = "1.5.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["preserve_order", "indexmap", "unbounded_depth"] }
statrs = { version = "0.15.0", features = [] }
strum = "0.24.0"
strum_macros = "0.24.0"
triple_accel = "0.4.0"
xz2 = "0.1.7"
zstd = { version = "0.11.2", features = ["zstdmt"] }

blas-src = { path = "../3rdparty/blas-src", features = ["intel-mkl-src"] }
intel-mkl-src = { path = "../3rdparty/intel-mkl-src/intel-mkl-src", default-features = false, features = ["download", "mkl-static-lp64-seq"] }
ndarray = { version = "0.15.4", features = ["rayon", "serde", "approx-0_5", "blas"] }
ndarray-linalg = { path = "../3rdparty/ndarray-linalg/ndarray-linalg", features = ["intel-mkl-static"] }
ndarray-rand = "0.14.0"
ndarray-stats = "0.5.0"
ndarray_einsum_beta = "0.7.0"


[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))'.dependencies]
mimalloc = { version = "0.1.28", default-features = false }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
pretty_assertions = "1.2.1"
rstest = "0.12.0"
rstest_reuse = "0.3.0"
