[package]
name = "treetime"
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
version.workspace = true


[lib]
crate-type = ["lib"]


[dependencies]
approx = { workspace = true }
argmin = { workspace = true }
bio = { workspace = true }
bio-types = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap-verbosity-flag = { workspace = true }
clap_complete = { workspace = true }
clap_complete_fig = { workspace = true }
color-eyre = { workspace = true }
csv = { workspace = true }
ctor = { workspace = true }
derive_more = { workspace = true }
env_logger = { workspace = true }
eyre = { workspace = true }
flate2 = { workspace = true }
gcollections = { workspace = true }
indexmap = { workspace = true }
intervallum = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
multimap = { workspace = true }
num = { workspace = true }
num-integer = { workspace = true }
num-traits = { workspace = true }
num_cpus = { workspace = true }
ordered-float = { workspace = true }
parking_lot = { workspace = true }
plotters = { workspace = true }
pretty_dtoa = { workspace = true }
rand = { workspace = true }
rand_distr = { workspace = true }
rand_isaac = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
rgb = { workspace = true }
rstat = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smart-default = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
time = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
atty = { workspace = true }
blas-src = { workspace = true }
bzip2 = { workspace = true }
crossterm = { workspace = true }
ndarray = { workspace = true }
ndarray-linalg = { workspace = true }
ndarray-rand = { workspace = true }
ndarray-stats = { workspace = true }
ndarray_einsum_beta = { workspace = true }
openblas-src = { workspace = true }
statrs = { workspace = true }
textplots = { workspace = true }
xz2 = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
pretty_assertions = { workspace = true }
rstest = { workspace = true }
rstest_reuse = { workspace = true }

[lints]
workspace = true
