[package]
name = "intel-mkl-tool"
version = "0.2.0+mkl2020.1"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

description = "CLI utility for redistributiing Intel(R) MKL"
repository  = "https://github.com/rust-math/intel-mkl-src"
keywords    = ["cli"]
license     = "MIT"

[features]
default = ["cli"]
archive = ["curl", "tar", "zstd"]
cli     = ["structopt", "archive"]

[dependencies]
anyhow = "1.0.31"
derive_more = "0.99.8"
dirs = "2.0.2"
glob = "0.3.0"
pkg-config = "0.3.17"

# archive
curl = { version = "0.4.29", optional = true }
tar  = { version = "0.4.29", optional = true }
zstd = { version = "0.11.2",  optional = true }

# CLI
structopt = { version = "0.3.15", optional = true }

[dev-dependencies]
paste = "0.1.17"

[[bin]]
name = "intel-mkl-tool"
path = "src/cli.rs"
required-features = ["cli"]

[package.metadata.release]
no-dev-version = true
