mod test_dense_sparse_equivalence_bounds;
mod test_dense_sparse_equivalence_convergence;
mod test_dense_sparse_equivalence_initial;
mod test_dense_sparse_equivalence_support;
mod test_dense_sparse_equivalence_validity;
