use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExponentialConvolutionTestCase {
  pub name: &'static str,
  pub description: &'static str,
  pub stress_type: &'static str,
  pub analytical_caution: &'static str,
  pub slowness: f64,
  pub a: f64,
  pub b: f64,
  pub input_grid_domain: (f64, f64),
  pub input_grid_n_points: usize,
}

pub const EXPONENTIAL_CONVOLUTION_CASES: &[ExponentialConvolutionTestCase] = &[
  ExponentialConvolutionTestCase {
    name: "python_notebook_case",
    description: "Parameters from conv_exp_py.ipynb: a=1, b=2",
    stress_type: "reference implementation validation",
    analytical_caution: "none",
    slowness: 0.0,
    a: 1.0,
    b: 2.0,
    input_grid_domain: (-1.0, 10.0),
    input_grid_n_points: 1101,
  },
  ExponentialConvolutionTestCase {
    name: "moderate_coarse_grid",
    description: "Moderate rates on a coarse grid. Discretization error on coarse grids; step size sensitivity.",
    stress_type: "aliasing/accuracy vs dx, dx scaling factor",
    analytical_caution: "none",
    slowness: 0.0,
    a: 1.0,
    b: 0.8,
    input_grid_domain: (0.0, 20.0),
    input_grid_n_points: 201,
  },
  ExponentialConvolutionTestCase {
    name: "tight_truncation",
    description: "Tight truncation to expose intentional errors. Sensitivity to insufficient support; boundary effects.",
    stress_type: "wrap-around artifacts if padding insufficient",
    analytical_caution: "none",
    slowness: 0.0,
    a: 1.0,
    b: 2.0,
    input_grid_domain: (0.0, 5.0),
    input_grid_n_points: 501,
  },
  ExponentialConvolutionTestCase {
    name: "baseline_distinct_rates",
    description: "Baseline with distinct rates (matches pdf example). General correctness, causal support, finite domains.",
    stress_type: "none",
    analytical_caution: "none",
    slowness: 0.0,
    a: 1.0,
    b: 2.0,
    input_grid_domain: (0.0, 10.0),
    input_grid_n_points: 1001,
  },
  ExponentialConvolutionTestCase {
    name: "equal_rates_limit",
    description: "Equal-rate limit scenario. Correct handling of a=b using limit form x*exp(-ax).",
    stress_type: "kernel path selection, avoids division by zero",
    analytical_caution: "pdf formula undefined at a=b; use limit form",
    slowness: 0.0,
    a: 1.5,
    b: 1.5,
    input_grid_domain: (0.0, 12.0),
    input_grid_n_points: 1201,
  },
  ExponentialConvolutionTestCase {
    name: "near_equal_rates",
    description: "Near-equal rates, cancellation sensitive. Numerical stability around a~b; sensitivity to expm1-style evaluation.",
    stress_type: "discretization over long horizons, accumulation error",
    analytical_caution: "use stable expm1 form for (1-exp(-(a-b)x))/(a-b)",
    slowness: 0.6,
    a: 1.0,
    b: 1.0 + 1e-6,
    input_grid_domain: (0.0, 30.0),
    input_grid_n_points: 15001,
  },
  ExponentialConvolutionTestCase {
    name: "fast_slow_decay",
    description: "Fast plus slow decay with wide dynamic range. Interaction of very fast and very slow decays; long-tail coverage.",
    stress_type: "truncation strategy for long g tail, FFT zero-padding",
    analytical_caution: "underflow in far tail contributions acceptable",
    slowness: 1.0,
    a: 10.0,
    b: 0.1,
    input_grid_domain: (0.0, 200.0),
    input_grid_n_points: 200001,
  },
  ExponentialConvolutionTestCase {
    name: "slow_fast_decay",
    description: "Slow plus fast decay swapping roles. Symmetry under role swap; causal truncation interaction.",
    stress_type: "padding and index handling at short g support",
    analytical_caution: "none",
    slowness: 1.0,
    a: 0.1,
    b: 10.0,
    input_grid_domain: (0.0, 200.0),
    input_grid_n_points: 200001,
  },
  ExponentialConvolutionTestCase {
    name: "fine_grid_reference",
    description: "High-accuracy fine grid reference baseline. Useful for regression against the coarse grid scenario.",
    stress_type: "performance/memory, summation order",
    analytical_caution: "none",
    slowness: 0.9,
    a: 1.0,
    b: 0.8,
    input_grid_domain: (0.0, 20.0),
    input_grid_n_points: 10001,
  },
  ExponentialConvolutionTestCase {
    name: "long_horizon_tail_precision",
    description: "Long horizon tail precision focus. Accumulation of small tail mass over long support.",
    stress_type: "FFT padding to avoid circular wrap, cumulative round-off",
    analytical_caution: "underflow in far tails expected",
    slowness: 0.95,
    a: 0.05,
    b: 0.04,
    input_grid_domain: (0.0, 750.0),
    input_grid_n_points: 75001,
  },
  ExponentialConvolutionTestCase {
    name: "large_range_underflow_guard",
    description: "Large x range with near-underflow guard. Stability across wide index ranges; causal support check.",
    stress_type: "exponent range, padding, accumulation depth",
    analytical_caution: "far tails may underflow to zero; acceptable",
    slowness: 0.7,
    a: 0.5,
    b: 0.7,
    input_grid_domain: (0.0, 400.0),
    input_grid_n_points: 20001,
  },
  ExponentialConvolutionTestCase {
    name: "extreme_near_equality",
    description: "Extreme near equality at machine epsilon scale. Robustness using expm1 and stable division.",
    stress_type: "long support convolution accuracy, summation stability",
    analytical_caution: "direct formula ill-conditioned; use stable evaluation",
    slowness: 0.65,
    a: 1.0,
    b: 1.0 + 1e-12,
    input_grid_domain: (0.0, 80.0),
    input_grid_n_points: 16001,
  },
  ExponentialConvolutionTestCase {
    name: "very_fast_decays",
    description: "Very fast decays on small domains. Accuracy on sharply localized causal signals.",
    stress_type: "grid resolution and dx scaling",
    analytical_caution: "none",
    slowness: 0.0,
    a: 25.0,
    b: 30.0,
    input_grid_domain: (0.0, 0.5),
    input_grid_n_points: 1001,
  },
];
