use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GaussianConvolutionTestCase {
  pub name: &'static str,
  pub description: &'static str,
  pub stress_type: &'static str,
  pub analytical_caution: &'static str,
  pub slowness: f64,
  pub sigma_f: f64,
  pub sigma_g: f64,
  pub mu: f64,
  pub input_grid_domain: (f64, f64),
  pub input_grid_n_points: usize,
}

pub const GAUSSIAN_CONVOLUTION_CASES: &[GaussianConvolutionTestCase] = &[
  GaussianConvolutionTestCase {
    name: "python_notebook_case_1",
    description: "Parameters from conv_gauss_py.ipynb: sigma_f=1, sigma_g=1, mu=1",
    stress_type: "reference implementation validation",
    analytical_caution: "none",
    slowness: 0.0,
    sigma_f: 1.0,
    sigma_g: 1.0,
    mu: 1.0,
    input_grid_domain: (-5.0, 5.0),
    input_grid_n_points: 101,
  },
  GaussianConvolutionTestCase {
    name: "python_notebook_case_2",
    description: "Parameters from conv_gauss_py.ipynb: sigma_f=2, sigma_g=1, mu=1",
    stress_type: "reference implementation validation",
    analytical_caution: "none",
    slowness: 0.0,
    sigma_f: 2.0,
    sigma_g: 1.0,
    mu: 1.0,
    input_grid_domain: (-5.0, 5.0),
    input_grid_n_points: 101,
  },
  GaussianConvolutionTestCase {
    name: "tight_truncation",
    description: "Tight truncation highlighting sensitivity to insufficient domain coverage.",
    stress_type: "boundary effects, wrap-around",
    analytical_caution: "none",
    slowness: 0.02,
    sigma_f: 1.0,
    sigma_g: 2.0,
    mu: 0.0,
    input_grid_domain: (-6.0, 6.0),
    input_grid_n_points: 1201,
  },
  GaussianConvolutionTestCase {
    name: "coarse_grid",
    description: "Coarse grid coverage emphasizing discretization error with sub-grid shift.",
    stress_type: "aliasing, grid spacing scaling",
    analytical_caution: "none",
    slowness: 0.0,
    sigma_f: 1.0,
    sigma_g: 1.0,
    mu: 0.5,
    input_grid_domain: (-8.0, 8.0),
    input_grid_n_points: 161,
  },
  GaussianConvolutionTestCase {
    name: "baseline_moderate",
    description: "Baseline scenario with moderate widths; general correctness with asymmetric widths and shift.",
    stress_type: "none",
    analytical_caution: "none",
    slowness: 0.07,
    sigma_f: 1.0,
    sigma_g: 2.0,
    mu: 1.0,
    input_grid_domain: (-12.0, 14.0),
    input_grid_n_points: 2601,
  },
  GaussianConvolutionTestCase {
    name: "centered_unequal_widths",
    description: "Centered configuration with unequal widths; width mixing and peak alignment at x=0.",
    stress_type: "resolution vs narrow kernel",
    analytical_caution: "none",
    slowness: 0.05,
    sigma_f: 1.5,
    sigma_g: 0.5,
    mu: 0.0,
    input_grid_domain: (-12.0, 12.0),
    input_grid_n_points: 2401,
  },
  GaussianConvolutionTestCase {
    name: "delta_like_small_shift",
    description: "Sharp g with small shift; sensitivity to sub-grid shifts and near-delta kernel behavior.",
    stress_type: "discretization error, normalization",
    analytical_caution: "potential overflow for large |x|/sigma_g",
    slowness: 0.8,
    sigma_f: 1.0,
    sigma_g: 0.05,
    mu: 0.2,
    input_grid_domain: (-8.0, 8.0),
    input_grid_n_points: 8001,
  },
  GaussianConvolutionTestCase {
    name: "wide_kernel_negative_shift",
    description: "Very wide g with negative shift; robustness to ultra-broad kernel tails and translation.",
    stress_type: "tail truncation, numeric underflow, FFT padding",
    analytical_caution: "underflow in far tails expected",
    slowness: 0.09,
    sigma_f: 0.5,
    sigma_g: 5.0,
    mu: -1.0,
    input_grid_domain: (-41.0, 39.0),
    input_grid_n_points: 4001,
  },
  GaussianConvolutionTestCase {
    name: "large_positive_shift",
    description: "Large positive shift validating translation invariance for sizeable mu.",
    stress_type: "circular convolution artifacts, insufficient padding",
    analytical_caution: "none",
    slowness: 0.08,
    sigma_f: 1.0,
    sigma_g: 1.2,
    mu: 10.0,
    input_grid_domain: (-10.0, 22.0),
    input_grid_n_points: 3201,
  },
  GaussianConvolutionTestCase {
    name: "large_negative_shift",
    description: "Large negative shift exercising translation invariance for negative mu.",
    stress_type: "padding and index handling",
    analytical_caution: "none",
    slowness: 0.06,
    sigma_f: 2.0,
    sigma_g: 1.0,
    mu: -7.0,
    input_grid_domain: (-16.0, 16.0),
    input_grid_n_points: 3201,
  },
  GaussianConvolutionTestCase {
    name: "extreme_ratio_wide_g",
    description: "Extreme width ratio with g much wider than f; convolution where g is nearly constant over f's support.",
    stress_type: "tail coverage, numerical cancellation",
    analytical_caution: "underflow in extreme tails",
    slowness: 0.75,
    sigma_f: 0.1,
    sigma_g: 10.0,
    mu: 3.0,
    input_grid_domain: (-77.0, 83.0),
    input_grid_n_points: 16001,
  },
  GaussianConvolutionTestCase {
    name: "extreme_ratio_wide_f",
    description: "Extreme width ratio with f much wider than g; near-delta g translating f.",
    stress_type: "grid resolution near narrow kernel peak",
    analytical_caution: "potential overflow if domain widened",
    slowness: 0.75,
    sigma_f: 8.0,
    sigma_g: 0.2,
    mu: -2.5,
    input_grid_domain: (-64.0, 64.0),
    input_grid_n_points: 6401,
  },
  GaussianConvolutionTestCase {
    name: "tail_precision_stress",
    description: "Tail precision stress with accurate accumulation of tiny tail mass.",
    stress_type: "truncation strategy, FFT padding",
    analytical_caution: "underflow to zero at extreme |x|",
    slowness: 0.88,
    sigma_f: 3.0,
    sigma_g: 4.0,
    mu: 0.0,
    input_grid_domain: (-48.0, 48.0),
    input_grid_n_points: 9601,
  },
  GaussianConvolutionTestCase {
    name: "fine_grid_reference",
    description: "Reference-quality very fine grid; high-accuracy baseline closest to analytical target.",
    stress_type: "performance/memory, summation order",
    analytical_caution: "none",
    slowness: 0.8,
    sigma_f: 1.0,
    sigma_g: 1.0,
    mu: 0.0,
    input_grid_domain: (-8.0, 8.0),
    input_grid_n_points: 8001,
  },
  GaussianConvolutionTestCase {
    name: "wide_dynamic_range",
    description: "Wide dynamic range with simultaneous handling of very sharp and very broad scales.",
    stress_type: "catastrophic cancellation, summation stability",
    analytical_caution: "under/overflow risks",
    slowness: 1.0,
    sigma_f: 0.05,
    sigma_g: 7.5,
    mu: 6.0,
    input_grid_domain: (-54.0, 66.0),
    input_grid_n_points: 24001,
  },
  GaussianConvolutionTestCase {
    name: "overflow_guard",
    description: "Near-overflow guard ensuring numerical stability over very wide grids.",
    stress_type: "padding, exponent range, accumulation depth",
    analytical_caution: "underflow in far tails expected",
    slowness: 0.9,
    sigma_f: 2.0,
    sigma_g: 2.5,
    mu: 0.0,
    input_grid_domain: (-100.0, 100.0),
    input_grid_n_points: 10001,
  },
  GaussianConvolutionTestCase {
    name: "tiny_shift_equal_widths",
    description: "Tiny shift with equal widths; sensitivity to small translations and symmetry properties.",
    stress_type: "interpolation/rounding at sub-grid peaks",
    analytical_caution: "none",
    slowness: 0.04,
    sigma_f: 1.25,
    sigma_g: 1.25,
    mu: 0.05,
    input_grid_domain: (-10.0, 10.05),
    input_grid_n_points: 2006,
  },
];
