use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GaussianPairwiseMultiplicationTestCase {
  pub name: &'static str,
  pub description: &'static str,
  pub stress_type: &'static str,
  pub analytical_caution: &'static str,
  pub slowness: f64,
  pub mu_f: f64,
  pub sigma_f: f64,
  pub amplitude_f: f64,
  pub mu_g: f64,
  pub sigma_g: f64,
  pub amplitude_g: f64,
  pub input_grid_domain: (f64, f64),
  pub input_grid_n_points: usize,
}

pub const GAUSSIAN_PAIRWISE_MULTIPLICATION_CASES: &[GaussianPairwiseMultiplicationTestCase] = &[
  GaussianPairwiseMultiplicationTestCase {
    name: "identical",
    description: "Two identical Gaussians at origin with unit amplitude.",
    stress_type: "baseline",
    analytical_caution: "none",
    slowness: 0.0,
    mu_f: 0.0,
    sigma_f: 1.0,
    amplitude_f: 1.0,
    mu_g: 0.0,
    sigma_g: 1.0,
    amplitude_g: 1.0,
    input_grid_domain: (-5.0, 5.0),
    input_grid_n_points: 201,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "shifted_equal",
    description: "Two Gaussians with equal widths but shifted means; product peak at midpoint.",
    stress_type: "translation",
    analytical_caution: "none",
    slowness: 0.0,
    mu_f: -1.0,
    sigma_f: 1.0,
    amplitude_f: 1.0,
    mu_g: 1.0,
    sigma_g: 1.0,
    amplitude_g: 1.0,
    input_grid_domain: (-6.0, 6.0),
    input_grid_n_points: 241,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "different_widths",
    description: "Two Gaussians with different widths; narrower Gaussian dominates result.",
    stress_type: "width mixing",
    analytical_caution: "none",
    slowness: 0.0,
    mu_f: 0.0,
    sigma_f: 1.0,
    amplitude_f: 1.0,
    mu_g: 0.0,
    sigma_g: 2.0,
    amplitude_g: 1.0,
    input_grid_domain: (-10.0, 10.0),
    input_grid_n_points: 401,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "narrow_wide",
    description: "Extreme width ratio with very narrow and very wide Gaussian.",
    stress_type: "extreme ratio, resolution",
    analytical_caution: "grid resolution may be insufficient for narrow Gaussian",
    slowness: 0.3,
    mu_f: 0.0,
    sigma_f: 0.1,
    amplitude_f: 1.0,
    mu_g: 0.0,
    sigma_g: 10.0,
    amplitude_g: 1.0,
    input_grid_domain: (-5.0, 5.0),
    input_grid_n_points: 1001,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "shifted_different_widths",
    description: "Shifted means with different widths; tests combined effects.",
    stress_type: "combined",
    analytical_caution: "none",
    slowness: 0.1,
    mu_f: -2.0,
    sigma_f: 1.5,
    amplitude_f: 1.0,
    mu_g: 1.0,
    sigma_g: 0.8,
    amplitude_g: 1.0,
    input_grid_domain: (-8.0, 8.0),
    input_grid_n_points: 321,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "small_amplitudes",
    description: "Small amplitudes testing log-scale handling.",
    stress_type: "underflow",
    analytical_caution: "numerical underflow possible with plain multiplication",
    slowness: 0.1,
    mu_f: 0.0,
    sigma_f: 1.0,
    amplitude_f: 0.001,
    mu_g: 0.0,
    sigma_g: 1.0,
    amplitude_g: 0.001,
    input_grid_domain: (-5.0, 5.0),
    input_grid_n_points: 201,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "large_shift",
    description: "Large shift between means; product has low amplitude.",
    stress_type: "near-zero product",
    analytical_caution: "product may underflow",
    slowness: 0.2,
    mu_f: -5.0,
    sigma_f: 1.0,
    amplitude_f: 1.0,
    mu_g: 5.0,
    sigma_g: 1.0,
    amplitude_g: 1.0,
    input_grid_domain: (-10.0, 10.0),
    input_grid_n_points: 401,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "asymmetric_shift",
    description: "Asymmetric shift with different widths.",
    stress_type: "asymmetry",
    analytical_caution: "none",
    slowness: 0.15,
    mu_f: 0.0,
    sigma_f: 2.0,
    amplitude_f: 1.0,
    mu_g: 3.0,
    sigma_g: 1.0,
    amplitude_g: 1.0,
    input_grid_domain: (-8.0, 12.0),
    input_grid_n_points: 401,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "fine_grid",
    description: "High-resolution grid for reference accuracy.",
    stress_type: "performance",
    analytical_caution: "none",
    slowness: 0.5,
    mu_f: 0.0,
    sigma_f: 1.0,
    amplitude_f: 1.0,
    mu_g: 0.5,
    sigma_g: 1.5,
    amplitude_g: 1.0,
    input_grid_domain: (-8.0, 8.0),
    input_grid_n_points: 3201,
  },
  GaussianPairwiseMultiplicationTestCase {
    name: "mixed_amplitudes",
    description: "Different amplitudes testing scale handling.",
    stress_type: "scale mixing",
    analytical_caution: "none",
    slowness: 0.1,
    mu_f: 0.0,
    sigma_f: 1.0,
    amplitude_f: 10.0,
    mu_g: 0.0,
    sigma_g: 1.0,
    amplitude_g: 0.5,
    input_grid_domain: (-5.0, 5.0),
    input_grid_n_points: 201,
  },
];
