use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GaussianExponentialTestCase {
  pub name: &'static str,
  pub description: &'static str,
  pub stress_type: &'static str,
  pub analytical_caution: &'static str,
  pub slowness: f64,
  pub a_f: f64,
  pub input_grid_domain: (f64, f64),
  pub input_grid_n_points: usize,
}

pub const GAUSSIAN_EXPONENTIAL_CASES: &[GaussianExponentialTestCase] = &[
  GaussianExponentialTestCase {
    name: "python_notebook_case",
    description: "Parameters from conv_gauss_exp.ipynb: a_f=0.5",
    stress_type: "reference implementation validation",
    analytical_caution: "none",
    slowness: 0.0,
    a_f: 0.5,
    input_grid_domain: (-5.0, 40.0),
    input_grid_n_points: 101,
  },
  GaussianExponentialTestCase {
    name: "python_notebook_case_fine",
    description: "Parameters from conv_gauss_exp.ipynb: a_f=0.5 with fine grid",
    stress_type: "reference implementation validation",
    analytical_caution: "none",
    slowness: 0.0,
    a_f: 0.5,
    input_grid_domain: (-5.0, 40.0),
    input_grid_n_points: 501,
  },
  GaussianExponentialTestCase {
    name: "coarse_grid",
    description: "Coarse discretization stress test with 51 points",
    stress_type: "discretization stress",
    analytical_caution: "coarse grid may miss fine structure",
    slowness: 0.1,
    a_f: 0.5,
    input_grid_domain: (-5.0, 40.0),
    input_grid_n_points: 51,
  },
  GaussianExponentialTestCase {
    name: "fine_grid_reference",
    description: "High-accuracy baseline with 1001 points",
    stress_type: "high resolution reference",
    analytical_caution: "none",
    slowness: 0.3,
    a_f: 0.5,
    input_grid_domain: (-5.0, 40.0),
    input_grid_n_points: 1001,
  },
  GaussianExponentialTestCase {
    name: "tight_truncation",
    description: "Tight domain truncation (-2 to 15) cutting distribution tails",
    stress_type: "domain truncation",
    analytical_caution: "truncated tails may cause boundary artifacts",
    slowness: 0.2,
    a_f: 0.5,
    input_grid_domain: (-2.0, 15.0),
    input_grid_n_points: 201,
  },
  GaussianExponentialTestCase {
    name: "wide_exponential",
    description: "Wide exponential with small a_f=0.1 for scale mismatch",
    stress_type: "scale mismatch",
    analytical_caution: "very different scales between Gaussian and exponential",
    slowness: 0.25,
    a_f: 0.1,
    input_grid_domain: (-5.0, 80.0),
    input_grid_n_points: 301,
  },
  GaussianExponentialTestCase {
    name: "fast_decay",
    description: "Fast exponential decay with a_f=2.0 for sharp localization",
    stress_type: "sharp localization",
    analytical_caution: "narrow peak requires adequate grid resolution",
    slowness: 0.15,
    a_f: 2.0,
    input_grid_domain: (-5.0, 15.0),
    input_grid_n_points: 201,
  },
];
