name: "Nightly CLI"

on:
  schedule:
    - cron: "0 4 * * *"

  workflow_dispatch:
    inputs:
      force:
        description: "Build even when source has not changed since the latest nightly"
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  nightly:
    uses: neherlab/treetime/.github/workflows/nightly.yml@rust
    with:
      force: ${{ inputs.force || false }}
    secrets: inherit
