#!/usr/bin/env bash
set -euo pipefail
trap "exit" INT
# shellcheck source=./../lib/utils.sh
source "${BASH_SOURCE%/*}/../lib/utils.sh"

# shellcheck disable=SC2046
file_hash \
  .dockerignore \
  .gitignore \
  rust-toolchain.toml \
  dev/lints/dylint/rust-toolchain.toml \
  dev/lints/mordant/rust-toolchain.toml \
  dev/lints/trailofbits/rust-toolchain.toml \
  mise.toml \
  mise.lock \
  $(find dev/docker -type f | sort)
