# syntax=docker/dockerfile:1
# check=experimental=all
FROM debian:12.14-slim@sha256:60eac759739651111db372c07be67863818726f754804b8707c90979bda511df

SHELL ["bash", "-euxo", "pipefail", "-c"]

ENV HOST_TUPLE_DEBIAN="x86_64-linux-gnu"
ENV HOST_TUPLE="x86_64-unknown-linux-gnu"
ENV HOST_TUPLE_UPPER="X86_64_UNKNOWN_LINUX_GNU"
ENV HOST_TUPLE_SAFE="x86_64_unknown_linux_gnu"
ENV HOST_GCC_TRIPLET="x86_64-unknown-linux-gnu"

ARG CROSS_COMPILE
ARG CROSS_COMPILE_UPPER
ARG CROSS_COMPILE_SAFE
ARG CROSS_APPLE_TRIPLET
ARG CROSS_GCC_TRIPLET

ENV CROSS_COMPILE="${CROSS_COMPILE}"
ENV CROSS_COMPILE_UPPER="${CROSS_COMPILE_UPPER}"
ENV CROSS_COMPILE_SAFE="${CROSS_COMPILE_SAFE}"
ENV CROSS_APPLE_TRIPLET="${CROSS_APPLE_TRIPLET}"
ENV CROSS_GCC_TRIPLET="${CROSS_GCC_TRIPLET}"

RUN set -euxo pipefail >/dev/null \
&& export DEBIAN_FRONTEND=noninteractive \
&& apt-get update -qq \
&& apt-get install --no-install-recommends --yes -qq \
  ca-certificates \
  curl \
  file \
  git \
  make \
  pigz \
  pixz \
  pkg-config \
  unzip \
  xz-utils \
  zstd \
>/dev/null \
&& apt-get clean autoclean >/dev/null \
&& apt-get autoremove --yes >/dev/null \
&& rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

COPY dev/docker/files/fetch dev/docker/files/checksums /

ENV PREFIX_HOST="/opt/host"
ENV HOST_GCC_DIR="${PREFIX_HOST}"
ENV PREFIX_CROSS="/opt/cross-${CROSS_COMPILE}"
ENV OSX_CROSS_PATH="/opt/osxcross"
ENV OPENBLAS_LIB_DIR="${PREFIX_CROSS}/lib"
COPY dev/docker/files/install-gcc-cross dev/docker/files/install-llvm dev/docker/files/install-protobuf dev/docker/files/install-osxcross dev/docker/files/install-openblas /
RUN set -euxo pipefail >/dev/null \
&& /install-gcc-cross "${HOST_TUPLE}" "${HOST_GCC_DIR}" \
&& /install-llvm "/usr/local" \
&& /install-protobuf "/usr/local" \
&& /install-osxcross "${OSX_CROSS_PATH}" \
&& /install-openblas "${CROSS_COMPILE}" "${PREFIX_CROSS}" \
&& rm /install-gcc-cross /install-llvm /install-protobuf /install-osxcross /install-openblas

ENV OSXCROSS_MP_INC="1"
ENV MACOSX_DEPLOYMENT_TARGET="10.12"
ENV PATH="${OSX_CROSS_PATH}/bin:${PATH}"
ENV CROSS_SYSROOT="${OSX_CROSS_PATH}/SDK/MacOSX11.1.sdk"

ENV CC_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-clang"
ENV CXX_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-clang++"
ENV FC_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_GCC_TRIPLET}-gfortran"
ENV AR_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-ar"
ENV AS_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-as"
ENV DSYMUTIL_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-dsymutil"
ENV LD_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-ld"
ENV LIBTOOL_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-libtool"
ENV LIPO_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-lipo"
ENV NM_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-nm"
ENV OBJDUMP_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-ObjectDump"
ENV OTOOL_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-otool"
ENV RANLIB_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-ranlib"
ENV STRIP_${CROSS_COMPILE_SAFE}="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-strip"

ENV BINDGEN_EXTRA_CLANG_ARGS_${CROSS_COMPILE_SAFE}="--sysroot=${CROSS_SYSROOT}"
ENV CARGO_TARGET_${CROSS_COMPILE_UPPER}_AR="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-ar"
ENV CARGO_TARGET_${CROSS_COMPILE_UPPER}_LINKER="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-clang"
ENV CARGO_TARGET_${CROSS_COMPILE_UPPER}_STRIP="${OSX_CROSS_PATH}/bin/${CROSS_APPLE_TRIPLET}-strip"

ENV HOST_SYSROOT="${HOST_GCC_DIR}/${HOST_GCC_TRIPLET}/sysroot"

ENV HOST_GCC="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-gcc"
ENV HOST_GXX="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-g++"
ENV HOST_GFORTRAN="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-gfortran"
ENV HOST_CLANG="/usr/local/bin/clang"
ENV HOST_CLANGPP="/usr/local/bin/clang++"
ENV HOST_ADDR2LINE="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-addr2line"
ENV HOST_AR="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-gcc-ar"
ENV HOST_AS="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-as"
ENV HOST_CPP="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-cpp"
ENV HOST_ELFEDIT="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-elfedit"
ENV HOST_LD="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-ld"
ENV HOST_LDD="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-ldd"
ENV HOST_NM="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-gcc-nm"
ENV HOST_OBJCOPY="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-objcopy"
ENV HOST_OBJDUMP="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-objdump"
ENV HOST_RANLIB="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-gcc-ranlib"
ENV HOST_READELF="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-readelf"
ENV HOST_SIZE="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-size"
ENV HOST_STRINGS="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-strings"
ENV HOST_STRIP="${HOST_GCC_DIR}/bin/${HOST_GCC_TRIPLET}-strip"

ENV HOST_CC="${HOST_GCC}"
ENV HOST_CXX="${HOST_GXX}"
ENV HOST_FC="${HOST_GFORTRAN}"

ENV HOSTCC="${HOST_CC}"
ENV HOSTCXX="${HOST_CXX}"
ENV HOSTFC="${HOST_FC}"
ENV HOSTLD="${HOST_LD}"

ENV CC_${HOST_TUPLE_SAFE}="$HOST_GCC"
ENV CXX_${HOST_TUPLE_SAFE}="$HOST_GXX"
ENV GCC_${HOST_TUPLE_SAFE}="$HOST_GCC"
ENV GXX_${HOST_TUPLE_SAFE}="$HOST_GXX"
ENV CLANG_${HOST_TUPLE_SAFE}="$HOST_CLANG"
ENV CLANGPP_${HOST_TUPLE_SAFE}="$HOST_CLANGPP"
ENV FC_${HOST_TUPLE_SAFE}="$HOST_FC"
ENV ADDR2LINE_${HOST_TUPLE_SAFE}="$HOST_ADDR2LINE"
ENV AR_${HOST_TUPLE_SAFE}="$HOST_AR"
ENV AS_${HOST_TUPLE_SAFE}="$HOST_AS"
ENV CPP_${HOST_TUPLE_SAFE}="$HOST_CPP"
ENV ELFEDIT_${HOST_TUPLE_SAFE}="$HOST_ELFEDIT"
ENV LD_${HOST_TUPLE_SAFE}="$HOST_LD"
ENV LDD_${HOST_TUPLE_SAFE}="$HOST_LDD"
ENV NM_${HOST_TUPLE_SAFE}="$HOST_NM"
ENV OBJCOPY_${HOST_TUPLE_SAFE}="$HOST_OBJCOPY"
ENV OBJDUMP_${HOST_TUPLE_SAFE}="$HOST_OBJDUMP"
ENV RANLIB_${HOST_TUPLE_SAFE}="$HOST_RANLIB"
ENV READELF_${HOST_TUPLE_SAFE}="$HOST_READELF"
ENV SIZE_${HOST_TUPLE_SAFE}="$HOST_SIZE"
ENV STRINGS_${HOST_TUPLE_SAFE}="$HOST_STRINGS"
ENV STRIP_${HOST_TUPLE_SAFE}="$HOST_STRIP"

ENV BINDGEN_EXTRA_CLANG_ARGS_${HOST_TUPLE_SAFE}="--sysroot=${HOST_SYSROOT}"
ENV CARGO_TARGET_${HOST_TUPLE_UPPER}_AR="${HOST_AR}"
ENV CARGO_TARGET_${HOST_TUPLE_UPPER}_LINKER="${HOST_GCC}"
ENV CARGO_TARGET_${HOST_TUPLE_UPPER}_STRIP="${HOST_STRIP}"

ENV CROSS_C_INCLUDE_PATH="${PREFIX_CROSS}/include"
ENV HOST_C_INCLUDE_PATH="${PREFIX_HOST}/include:${HOST_GCC_DIR}/include"

ENV CROSS_CPLUS_INCLUDE_PATH="${CROSS_C_INCLUDE_PATH}"
ENV HOST_CPLUS_INCLUDE_PATH="${HOST_C_INCLUDE_PATH}"

ENV CROSS_LIBRARY_PATH="${PREFIX_CROSS}/lib:${PREFIX_CROSS}/lib64:${OSX_CROSS_PATH}/lib/gcc/${CROSS_APPLE_TRIPLET}/14.2.0:${OSX_CROSS_PATH}/lib/gcc/${CROSS_GCC_TRIPLET}/14.2.0"
ENV HOST_LIBRARY_PATH="${HOST_GCC_DIR}/lib:${HOST_GCC_DIR}/lib64"

ENV C_INCLUDE_PATH="${CROSS_C_INCLUDE_PATH}:${HOST_C_INCLUDE_PATH}"
ENV CPLUS_INCLUDE_PATH="${CROSS_CPLUS_INCLUDE_PATH}:${HOST_CPLUS_INCLUDE_PATH}"
ENV LIBRARY_PATH="${CROSS_LIBRARY_PATH}:${HOST_LIBRARY_PATH}"

ENV C_INCLUDE_PATH_${HOST_TUPLE_SAFE}="${HOST_C_INCLUDE_PATH}"
ENV CPLUS_INCLUDE_PATH_${HOST_TUPLE_SAFE}="${HOST_CPLUS_INCLUDE_PATH}"
ENV LIBRARY_PATH_${HOST_TUPLE_SAFE}="${HOST_LIBRARY_PATH}"

ENV C_INCLUDE_PATH_${CROSS_COMPILE_SAFE}="${CROSS_C_INCLUDE_PATH}"
ENV CPLUS_INCLUDE_PATH_${CROSS_COMPILE_SAFE}="${CROSS_CPLUS_INCLUDE_PATH}"
ENV LIBRARY_PATH_${CROSS_COMPILE_SAFE}="${CROSS_LIBRARY_PATH}"

ENV CROSS_PKG_CONFIG_PATH="${PREFIX_CROSS}/lib/pkgconfig:${PREFIX_CROSS}/lib64/pkgconfig"
ENV HOST_PKG_CONFIG_PATH="${HOST_GCC_DIR}/lib/pkgconfig:${HOST_GCC_DIR}/lib64/pkgconfig"
ENV PKG_CONFIG_PATH="${CROSS_PKG_CONFIG_PATH}:${HOST_PKG_CONFIG_PATH}"
ENV PKG_CONFIG_ALLOW_CROSS="1"

ENV PKG_CONFIG_PATH_${HOST_TUPLE_SAFE}="${HOST_PKG_CONFIG_PATH}"
ENV PKG_CONFIG_SYSROOT_DIR_${HOST_TUPLE_SAFE}="${PREFIX_HOST}"

ENV PKG_CONFIG_PATH_${CROSS_COMPILE_SAFE}="${CROSS_PKG_CONFIG_PATH}"
ENV PKG_CONFIG_SYSROOT_DIR_${CROSS_COMPILE_SAFE}="${PREFIX_CROSS}"

ENV PKG_CONFIG_SYSROOT_DIR="${PREFIX_CROSS}"

ENV CMAKE_PREFIX_PATH="${PREFIX_CROSS}"

ENV LD_LIBRARY_PATH="${OSX_CROSS_PATH}/lib"

# The Rust toolchain of rust-toolchain.toml with the target. dev/docker/run runs
# as the host user with HOME=/tmp/home and the cargo home in the checkout.
ENV RUSTUP_HOME="/usr/local/rustup"
ENV CARGO_HOME="/usr/local/cargo"
ENV PATH="/usr/local/cargo/bin:${PATH}"
COPY dev/docker/files/install-rust /
COPY rust-toolchain.toml /tmp/rust/
RUN set -euxo pipefail >/dev/null \
&& /install-rust "/tmp/rust" "${CROSS_COMPILE}" \
&& rm -rf /install-rust /tmp/rust \
&& mkdir -p "/tmp/home" \
&& chmod 1777 "/tmp/home"
