#!/usr/bin/env bash
#
# Usage: dev/docker/jupyter
#
# Start JupyterLab in the Python image of TreeTime v0 on port JUPYTER_PORT
# (default 10000).
#
set -euo pipefail

TREETIME_DOCKER_IMAGE=jupyter exec "$(dirname "${BASH_SOURCE[0]}")/run" /start-jupyter
